name: Keep Supabase Alive

on:
  schedule:
    # 每天 UTC 时间 00:00 运行一次 (北京时间早上 8:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点击按钮运行

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET '${{ secrets.SUPABASE_URL }}/rest/v1/study_logs?select=*&limit=1' \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
